# Generated by Django 6.0.7 on 2026-07-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_code', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_code', models.CharField(blank=True, max_length=10)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('department', models.CharField(choices=[('SERVICES', 'خدمات'), ('SECURITY', 'حراست'), ('LAUNDRY', 'لاندری'), ('CSSD', 'CSSD'), ('WAREHOUSE', 'انبار خدمات'), ('TRANSPORT', 'حمل و نقل')], default='SERVICES', max_length=20)),
                ('job_title', models.CharField(max_length=100)),
                ('hire_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
