# Generated by Django 6.0.7 on 2026-07-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('SERVICES', 'خدمات'), ('SECURITY', 'حراست'), ('LAUNDRY', 'لنژری'), ('CSR', 'CSR'), ('WAREHOUSE', 'انبار خدمات'), ('TRANSPORT', 'حمل و نقل')], default='SERVICES', max_length=20),
        ),
    ]
