# Generated by Django 6.0.7 on 2026-07-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('personnel_code', models.CharField(max_length=20, unique=True, verbose_name='کد پرسنلی')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('unit', models.CharField(choices=[('floor1', 'خدمات طبقه اول'), ('floor2', 'خدمات طبقه دوم'), ('thalassemia', 'خدمات تالاسمی'), ('laboratory', 'خدمات آزمایشگاه'), ('pharmacy', 'خدمات داروخانه'), ('linen', 'لنژری'), ('csr', 'CSR'), ('waste', 'پسماند'), ('patient_transport', 'بیماربر'), ('pantry_floor1', 'آبدارخانه طبقه اول'), ('pantry_floor3', 'آبدارخانه و سالن غذاخوری طبقه سوم'), ('security', 'حراست'), ('driver_official', 'راننده استخدامی'), ('driver_private', 'راننده خصوصی'), ('warehouse', 'انبار خدمات'), ('wheelchair', 'مدیریت ویلچر')], max_length=30, verbose_name='واحد')),
                ('employment_type', models.CharField(choices=[('shift', 'شیفتی'), ('fixed', 'ثابت')], default='fixed', max_length=10, verbose_name='نوع فعالیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پرسنل',
                'verbose_name_plural': 'پرسنل',
            },
        ),
    ]
